.PHONY: clean All

All:
	@echo "----------Building project:[ AltitudeMeter ]----------"
	"$(MAKE)" -f  "AltitudeMeter.mk"
clean:
	@echo "----------Cleaning project:[ AltitudeMeter ]----------"
	"$(MAKE)" -f  "AltitudeMeter.mk" clean
